#pragma once

#define DO_OPTIMIZATION 1
#define VERBOSE 0
#define OPTVERBOSE 0
#define UNFLATTENVERBOSE 1
#define UNFLATTENDEBUG 1
#define MMAT_DEOB_MAP MMAT_LOCOPT
//#define MMAT_DEOB_UNFLATTEN MMAT_CALLS
#define MMAT_DEOB_UNFLATTEN MMAT_GLBOPT2
#define USE_HEXRAYS_CALLBACK 1

